# Rendered by cc-theme-set from ~/.config/cc/templates/zathurarc.tpl
set font "JetBrainsMono Nerd Font Bold 11"
set default-bg "{{ background }}"
set default-fg "{{ foreground }}"
set statusbar-bg "{{ dark_background }}"
set statusbar-fg "{{ foreground }}"
set inputbar-bg "{{ background }}"
set inputbar-fg "{{ foreground }}"
set notification-bg "{{ background }}"
set notification-fg "{{ foreground }}"
set notification-error-bg "{{ red }}"
set notification-error-fg "{{ background }}"
set notification-warning-bg "{{ yellow }}"
set notification-warning-fg "{{ background }}"
set highlight-color "{{ accent }}"
set highlight-active-color "{{ selection_background }}"
set completion-bg "{{ dark_background }}"
set completion-fg "{{ foreground }}"
set completion-highlight-bg "{{ accent }}"
set completion-highlight-fg "{{ background }}"
set completion-group-bg "{{ background }}"
set completion-group-fg "{{ accent }}"
set index-bg "{{ background }}"
set index-fg "{{ foreground }}"
set index-active-bg "{{ accent }}"
set index-active-fg "{{ background }}"
set recolor-lightcolor "{{ background }}"
set recolor-darkcolor "{{ foreground }}"
set recolor-keephue true
